import {guideReference} from './guide.mjs';

export function guideLevelButtons(level,act='help-level'){
 return `<div class="guide-levels" role="group" aria-label="Nivel de la ayuda"><button type="button" data-act="${act}" data-level="basic" aria-pressed="${level!=='advanced'}">Básico · empezar</button><button type="button" data-act="${act}" data-level="advanced" aria-pressed="${level==='advanced'}">Avanzado · profundizar</button></div>`;
}

export function guideView(state,bundle,level,{esc,fmt,icon}){
 const model=guideReference(state,bundle),advanced=level==='advanced';
 const costs=c=>`${fmt(c.budget)} caja · ${fmt(c.energy)} energía`;
 const values=model.resources.filter(r=>['budget','energy'].includes(r.id)).map(r=>`<div><strong>${esc(r.label)}${r.value!==undefined?` · ${fmt(r.value)} / ${fmt(r.max)}`:''}</strong><p>${r.id==='budget'?'Paga tus jugadas y el trabajo del equipo.':'Permite salir al candidato. Descansar la recupera.'}</p></div>`).join('');
 const basic=`<p class="guide-intro">Elige tu jugada, revisa <strong>caja y energía</strong> y pulsa Jugar. Puedes aceptar las tareas que propone el equipo.</p>
 <div class="guide-loop" aria-label="Orden de un turno"><span>1. Responde a la noticia</span><span>2. Elige tu jugada</span><span>3. Revisa y pulsa Jugar</span><span>4. Mira qué cambió</span></div>
 <p class="guide-decision-note"><strong>Hay dos momentos distintos:</strong> Responder a una noticia aplica sus efectos al pulsar. Cambiar una jugada o tarea solo la prepara; se ejecuta con <strong>Jugar</strong>.</p>
 <h3>Tus cuatro jugadas</h3><div class="guide-actions">${model.actions.map(a=>`<article class="guide-action"><h4><span aria-hidden="true">${icon(a.id)}</span>${esc(a.label)}</h4><p class="guide-benefit">${esc(a.benefit)}</p><p>${esc(a.when)}</p><small>${esc(costs(a.cost))}</small></article>`).join('')}</div>
 <p class="guide-footnote">${esc(model.costScope)} Las ganancias tienen un límite: no puedes superar el máximo de cada recurso.</p>
 <div class="guide-resources-basic">${values}</div>
 <details class="guide-detail"><summary>Un primer turno, paso a paso</summary><p>Responde a la noticia. En el mapa, busca una provincia marcada como Ganar o Defender. Elige Visitar y revisa el coste de la jugada y del equipo. Si te encaja, pulsa Jugar. Después mira tu resultado y qué hicieron los rivales.</p><p>También puedes elegir Medios, Recaudar o Descansar. No hay una única jugada correcta.</p></details>
 <details class="guide-detail"><summary>Me he quedado sin recursos</summary><p><strong>Sin caja:</strong> Recaudar te da dinero para los próximos turnos, si tienes energía. Pon al equipo a Ahorrar si no puedes pagar sus tareas.</p><p><strong>Sin energía:</strong> Descansar es gratis. Si también falta caja, combina Descansar con Ahorrar en las dos tareas. Al cerrar el turno recuperas además hasta ${fmt(model.recovery)} de energía.</p></details>
 <p class="guide-footnote">La campaña dura ${fmt(model.turns)} turnos. Tu objetivo concreto aparece sobre el mapa. Los votos se convierten en escaños y después llegan los pactos; tener más escaños no garantiza formar Gobierno.</p>`;
 const advancedView=`<p class="guide-intro">Abre solo lo que necesites. Aquí ves qué aporta el equipo, para qué sirve cada parámetro y cómo convertir tu campaña en un acuerdo.</p>
 <details class="guide-detail"><summary>El equipo: qué gano con cada tarea</summary><p>Una tarea por colaborador disponible. Actúan <strong>antes del candidato</strong>; sus costes se suman al plan. Si una noticia ocupa a alguien, no puede hacer otra tarea ese turno.</p><div class="guide-task-list">${model.tasks.map(t=>`<article><h4>${esc(t.label)}</h4><p class="guide-benefit">${esc(t.benefit)}</p>${t.detail?`<p>${esc(t.detail)}</p>`:""}<p>${esc(t.when)}</p><small>${t.costs.map(c=>`${esc(c.name)}: ${c.readiness!==undefined?`hasta ${fmt(c.readiness)} fichas · `:""}${esc(costs(c))}`).join(' · ')}${t.nationalCost?` · Nacional: ${esc(costs(t.nationalCost))}`:''}</small></article>`).join('')}</div></details>
 <details class="guide-detail" id="guide-resources"><summary>Los parámetros: qué importa y por qué</summary><div class="guide-task-list">${model.resources.map(r=>`<article id="guide-resource-${r.id}" tabindex="-1"><h4>${esc(r.label)}${r.value!==undefined?` <span>${fmt(r.value)} / ${fmt(r.max)}</span>`:''}</h4><p>${esc(r.body)}</p></article>`).join('')}
 <article><h4>Organización local</h4><p>Equipos en una provincia que siguen aportando apoyo en cada cierre. Cuanto antes los organices, más turnos trabajan. Tienen un máximo y no garantizan un escaño.</p></article>
 <article><h4>Relaciones</h4><p>Con partidos, ayudan a negociar; el programa también debe encajar. Con asociaciones, abren conversaciones y posibles noticias. Son relaciones distintas y ninguna entrega votos por sí sola.</p></article></div></details>
 <details class="guide-detail"><summary>Medios, repetición y respuestas al rival</summary><p>Medios llega a las provincias donde compites y usa automáticamente una ficha de preparación si está disponible. ${model.modern?'Repetir entrevistas reduce su efecto hasta un mínimo; descansar entre ellas no reinicia esa pérdida.':'Las entrevistas repetidas pierden novedad en esta edición.'} Repetir visitas a la misma provincia también pierde fuerza.</p><p>Cuando un rival te ha atacado, puede aparecer <strong>Comparar</strong> dentro de Medios. Disputa apoyo y enfría la relación; también puede salir mal. Tener preparación reduce ese riesgo. Es una variante de tu única jugada, no una acción extra.</p><p>Las cifras de apoyo previstas no son escaños asegurados. Revisa los límites antes de insistir en una provincia saturada.</p></details>
 <details class="guide-detail"><summary>Noticias, debate y preparación</summary><p>Las noticias tienen consecuencias propias: pueden cambiar apoyo, reputación, cohesión, relaciones o recursos. Algunas abren un compromiso que volverá más adelante. Lee qué gana y pierde cada opción.</p><p>El debate tiene tres intervenciones. Algunas respuestas necesitan una ficha; otras son gratuitas. Guarda preparación antes de llegar: ensayar en la agenda posterior no mejora una respuesta que ya has dado.</p></details>
 <details class="guide-detail"><summary>El mapa: sondeos y último escaño</summary><p>El sondeo es una estimación. Ganar o Defender señala dónde está disputado un escaño. El margen en votos no dice cuántos votos dará una visita.</p><p>Tus acciones, los rivales y la incertidumbre del sondeo influyen en lo que ves. Afinar sondeo mejora la precisión; no aumenta tu apoyo. El reparto definitivo se calcula provincia a provincia al terminar la campaña.</p></details>
 <details class="guide-detail"><summary>Programa, prioridades y pactos</summary><p><strong>Posturas:</strong> qué defiendes sobre cada tema. Pueden atraer o alejar apoyo según la provincia y facilitar o dificultar acuerdos.</p><p><strong>Prioridades:</strong> los dos temas que elegiste proteger. En el pacto repartes las unidades disponibles; la pantalla indica qué conservas y a qué renuncias.</p><p>Antes de proponer, mira la previsión de síes, noes y abstenciones. Una buena relación abre la conversación; no basta si la oferta no encaja.</p><p><strong>Primera votación:</strong> 176 síes. <strong>Segunda:</strong> más síes que noes; una abstención puede facilitar el acuerdo.${Number.isFinite(bundle.config.negotiation.secondBallotRevisionCost)?` Entre tus dos votaciones puedes revisar una parte de tu propuesta por ${fmt(bundle.config.negotiation.secondBallotRevisionCost)} de caja, una sola vez: mira los apoyos antes de confirmar.`:''}</p></details>
 <details class="guide-detail"><summary>Guardar, continuar y repetir</summary><p>La partida se guarda en este navegador. Guardar descarga un archivo que puedes importar desde Inicio, también en otro dispositivo. Repetir conserva la candidatura y la clave para probar otras decisiones.</p><p>Si cambias de navegador o pasas de la versión local a la web, importa el archivo para continuar la misma partida.</p></details>`;
 return `${guideLevelButtons(level)}<div class="guide-content" id="guide-content">${advanced?advancedView:basic}</div><div class="button-row guide-return">${state?'<button type="button" data-act="tutorial-resume">Guiarme en la partida</button>':''}<button type="button" class="primary" data-act="close-dialog">${state?'Volver a mi campaña':'Entendido'}</button></div><p class="guide-footnote">Teclado: Tab recorre controles, Espacio marca opciones, Enter activa botones y Esc cierra esta ayuda.</p>`;
}
