import {guideReference} from './guide.mjs';

export function guideLevelButtons(level,act='help-level'){
 return `<div class="guide-levels" role="group" aria-label="Nivel de la ayuda"><button type="button" data-act="${act}" data-level="basic" aria-pressed="${level!=='advanced'}">Básico · empezar</button><button type="button" data-act="${act}" data-level="advanced" aria-pressed="${level==='advanced'}">Avanzado · profundizar</button></div>`;
}

export function guideView(state,bundle,level,{esc,fmt,icon}){
 const model=guideReference(state,bundle),advanced=level==='advanced';
 const costs=c=>`${fmt(c.budget)} de caja · ${fmt(c.energy)} de energía`;
 const visit=model.actions.find(a=>a.id==='visit');
 const values=model.resources.filter(r=>['budget','energy'].includes(r.id)).map(r=>`<div><strong>${esc(r.label)}${r.value!==undefined?` · ${fmt(r.value)} / ${fmt(r.max)}`:''}</strong><p>${r.id==='budget'?'Es el dinero disponible. Paga las jugadas y las tareas del equipo.':'Es la fuerza del candidato para actuar. Descansar la recupera.'}</p></div>`).join('');
 const basic=`<p class="guide-intro">Elige tu jugada, revisa <strong>caja y energía</strong> y pulsa Jugar. Puedes aceptar las tareas que propone el equipo.</p>
 <div class="guide-loop" aria-label="Orden de un turno"><span>1. Responde a la noticia</span><span>2. Elige tu jugada</span><span>3. Revisa y pulsa Jugar</span><span>4. Mira qué cambió</span></div>
 <p class="guide-decision-note"><strong>Cuándo decides:</strong> Al pulsar <strong>Responder</strong> en una noticia, la decisión se aplica al momento. Después puedes cambiar tu jugada y las tareas del equipo tantas veces como quieras: solo se ejecutan al pulsar <strong>Jugar</strong>.</p>
 <h3>Tus cuatro jugadas</h3><div class="guide-actions">${model.actions.map(a=>`<article class="guide-action"><h4><span aria-hidden="true">${icon(a.id)}</span>${esc(a.label)}</h4><p class="guide-benefit">${esc(a.benefit)}</p><p>${esc(a.when)}</p><small>${esc(costs(a.cost))}</small></article>`).join('')}</div>
 <p class="guide-footnote">${esc(model.costScope)} No puedes superar el máximo de cada recurso. Si una provincia ya está en tu máximo de apoyo, insistir allí no suma más.</p>
 <div class="guide-resources-basic">${values}</div>
 <details class="guide-detail"><summary>Un primer turno, paso a paso</summary><ol><li>Responde a la noticia: esa decisión se aplica al momento.</li><li>Busca en el mapa una provincia marcada como <strong>Ganar</strong>: según el sondeo, allí puedes quitarle un escaño a otro partido. Púlsala y elige <strong>Visitar</strong>.</li><li>La visita cuesta ${esc(costs(visit.cost))}. Para probar solo esa jugada, abre <strong>Cambiar tareas</strong> y pon a cada colaborador disponible a <strong>Ahorrar</strong>: el equipo añadirá 0 de caja al coste.</li><li>Si tienes recursos suficientes, pulsa <strong>Jugar</strong>. Después comprueba cuánto apoyo has ganado y qué hicieron los rivales. Ganar apoyo no siempre basta para conseguir otro escaño.</li></ol><p>Es un ejemplo para aprender los controles. También puedes mantener las tareas propuestas o elegir Medios, Recaudar o Descansar.</p></details>
 <details class="guide-detail"><summary>Me he quedado sin recursos</summary><p><strong>Sin caja:</strong> Recaudar te da dinero para los próximos turnos, si tienes energía. En Cambiar tareas, pon al equipo a Ahorrar si no puedes pagar sus tareas.</p><p><strong>Sin energía:</strong> Descansar es gratis. Si también falta caja, combina Descansar con Ahorrar en las dos tareas. Al terminar el turno recuperas además hasta ${fmt(model.recovery)} de energía.</p></details>
 <p class="guide-footnote">La campaña dura ${fmt(model.turns)} turnos. Tu objetivo concreto aparece sobre el mapa. Los votos se convierten en escaños y después llegan los pactos; tener más escaños no garantiza formar Gobierno.</p>`;
 const advancedView=`<p class="guide-intro">Abre solo lo que necesites. Aquí ves qué aporta el equipo, para qué sirve cada parámetro y cómo convertir tu campaña en un acuerdo.</p>
 <details class="guide-detail"><summary>El equipo: qué gano con cada tarea</summary><p>Una tarea por colaborador disponible. Actúan <strong>antes del candidato</strong>; sus costes se suman al plan. Si una noticia ocupa a alguien, no puede hacer otra tarea ese turno.</p><div class="guide-task-list">${model.tasks.map(t=>`<article><h4>${esc(t.label)}</h4><p class="guide-benefit">${esc(t.benefit)}</p>${t.detail?`<p>${esc(t.detail)}</p>`:""}<p>${esc(t.when)}</p><small>${t.costs.map(c=>`${esc(c.name)}: ${c.readiness!==undefined?`hasta ${fmt(c.readiness)} fichas · `:""}${esc(costs(c))}`).join(' · ')}${t.nationalCost?` · Nacional: ${esc(costs(t.nationalCost))}`:''}</small></article>`).join('')}</div></details>
 <details class="guide-detail" id="guide-resources"><summary>Los parámetros: qué importa y por qué</summary><div class="guide-task-list">${model.resources.map(r=>`<article id="guide-resource-${r.id}" tabindex="-1"><h4>${esc(r.label)}${r.value!==undefined?` <span>${fmt(r.value)} / ${fmt(r.max)}</span>`:''}</h4><p>${esc(r.body)}</p></article>`).join('')}
 <article><h4>Organización local</h4><p>Son tus equipos de voluntarios en una provincia. Suman apoyo al terminar cada turno, mientras quede margen para crecer. Cuanto antes los organices, más turnos trabajan. Hay un máximo de equipos por provincia y no aseguran un escaño.</p></article>
 <article><h4>Relaciones</h4><p>Indican cómo te llevas con cada partido o asociación. Una buena relación con un partido ayuda a pactar, pero la propuesta también debe encajarle. Con una asociación, puede abrir nuevas conversaciones o noticias; no significa que sus miembros vayan a votarte.</p></article></div></details>
 <details class="guide-detail"><summary>Medios, repetición y respuestas al rival</summary><p>Medios llega a las provincias donde compites y usa automáticamente una ficha de preparación si está disponible. ${model.modern?'Repetir entrevistas reduce su efecto hasta un mínimo; descansar entre ellas no reinicia esa pérdida.':'Las entrevistas repetidas pierden novedad en esta edición.'} Repetir visitas a la misma provincia también pierde fuerza.</p><p>Cuando un rival te ha atacado, puede aparecer <strong>Comparar</strong> dentro de Medios. Disputa apoyo y enfría la relación; también puede salir mal. Tener preparación reduce ese riesgo. Es una variante de tu única jugada, no una acción extra.</p><p>Las cifras de apoyo previstas no son escaños asegurados. Revisa los límites antes de insistir en una provincia saturada.</p></details>
 <details class="guide-detail"><summary>Noticias, debate y preparación</summary><p>Cada respuesta puede cambiar tu apoyo, tu imagen, la coordinación del equipo, tus relaciones o tus recursos. Si prometes contestar algo más adelante, el juego puede volver a preguntártelo. Compara qué ganas y a qué renuncias antes de responder.</p><p>El debate tiene tres intervenciones. Algunas respuestas cuestan una ficha de preparación; otras son gratuitas. Lleva fichas antes de empezar el debate.</p><p><strong>Ejemplo:</strong> si el equipo ensaya y después haces Medios, puedes usar una ficha recién ganada en esa jugada. Pero si ya has respondido al debate, ensayar después no cambia aquella respuesta.</p></details>
 <details class="guide-detail"><summary>El mapa: sondeos y último escaño</summary><p>El sondeo estima el resultado; todavía no son los votos definitivos. <strong>Ganar</strong> señala un escaño que puedes quitarle a un rival. <strong>Defender</strong> señala uno tuyo que puedes perder.</p><p><strong>Ejemplo:</strong> «faltan 500 votos» significa que el sondeo te sitúa a esa distancia del escaño. No significa que una visita vaya a darte 500 votos.</p><p>Los rivales también actúan y los sondeos tienen margen de error. Afinar sondeo te da una estimación más precisa; no consigue más apoyo. Los escaños definitivos se reparten provincia a provincia al terminar la campaña.</p></details>
 <details class="guide-detail"><summary>Programa, prioridades y pactos</summary><p><strong>Posturas:</strong> qué defiendes sobre cada tema. Pueden atraer o alejar apoyo según la provincia y facilitar o dificultar acuerdos.</p><p><strong>Prioridades:</strong> los dos temas que elegiste proteger. En el pacto repartes puntos entre los temas: cuantos más das a uno, más peso tiene en el acuerdo. Esos puntos no son dinero ni escaños. La pantalla indica qué conservas y a qué renuncias.</p><p>Antes de proponer, mira cuántos votarían sí, no o abstención. Llevarte bien con otro partido ayuda, pero la oferta también debe encajarle.</p><p><strong>Primera votación:</strong> necesitas al menos 176 síes. <strong>Segunda:</strong> basta con más síes que noes. Por ejemplo, 170 síes, 165 noes y 15 abstenciones no bastan en la primera, pero sí en la segunda.${Number.isFinite(bundle.config.negotiation.secondBallotRevisionCost)?` Si tu propuesta falla en la primera votación, puedes mover un punto de un tema a otro por ${fmt(bundle.config.negotiation.secondBallotRevisionCost)} de caja antes de volver a votar. Solo puedes hacerlo una vez: comprueba cómo cambian los apoyos antes de confirmar.`:''}</p></details>
 <details class="guide-detail"><summary>Guardar, continuar y repetir</summary><p>La partida se guarda automáticamente en este navegador. <strong>Guardar</strong> descarga una copia en un archivo. Puedes recuperarla con <strong>Importar</strong> desde Inicio, también en otro dispositivo.</p><p><strong>Repetir</strong> empieza de nuevo con tu candidato, equipo y condiciones iniciales, para probar otras decisiones.</p><p>Si cambias de navegador o pasas de la versión local a la web, importa el archivo para continuar la misma partida.</p></details>`;
 return `${guideLevelButtons(level)}<div class="guide-content" id="guide-content">${advanced?advancedView:basic}</div><div class="button-row guide-return">${state?'<button type="button" data-act="tutorial-resume">Guiarme en la partida</button>':''}<button type="button" class="primary" data-act="close-dialog">${state?'Volver a mi campaña':'Entendido'}</button></div><p class="guide-footnote">Teclado: Tab recorre controles, Espacio marca opciones, Enter activa botones y Esc cierra esta ayuda.</p>`;
}
